### ISSUE TITLE
Num Docs from generateUserUsageReport returns undefined

### ISSUE THREAD

**Issue by ianhyzy** [googleworkspace/apps-script-samples#126] opened 2019-08-06 19:34 UTC
## Expected Behavior
generateUserUsageReport should tell me how many new Docs a user made in the last week.

## Actual Behavior
Right now, it returns "undefined".
![image](https://user-images.githubusercontent.com/3400872/62571530-34434480-b857-11e9-8de6-e3ae511786ab.png)

## Steps to Reproduce the Problem

1. Paste the script
2. Run it
1. See undefined instead of the corect number

**Comment by erickoledadevrel** [comment] 2019-08-08 15:34
I tried reproduce this, but it's returning a number in my test account. What edition of G Suite are you using?

**Comment by ianhyzy** [comment] 2019-08-08 15:41
All users on the target domain have Enterprise.

**Comment by ianhyzy** [comment] 2019-08-08 15:44
Apologies, I should have mentioned this earlier - I was running this script inside of app maker and made sure I had all the advanced services turned on, so I assumed it wouldn't matter - but this script works fine on scripts.google.com for me, just not as an AM server script. I had all these services enabled on the project in case one of them was the issue:
![image](https://user-images.githubusercontent.com/3400872/62717395-6d9bc180-b9c9-11e9-8922-119b7590504d.png)

**Comment by erickoledadevrel** [comment] 2019-08-08 16:20
Ah, that's very useful information, thanks for confirming. And both times the code is run as the same user, who is a super admin in the G Suite organization?

**Comment by ianhyzy** [comment] 2019-08-08 17:09
Both times the code is run from the same superadmin account, right.

**Comment by suchi1788** [comment] 2020-10-01 00:30
I tried this on student appointment google sheet. If one of the cell is blank without email address. It doesn't send email to those whose email address is there. It means every students email address should be there in each cell in the range given then only it will run. Is there any other solution? Error comes "Failed to send email: no recipient (line 17, file "Sent Testing Email")

**Comment by sqrrrl** [comment] 2021-12-16 19:18
Closing since this seems to be specific to app maker which is no longer available.

**Closed by sqrrrl** 2021-12-16 19:18 UTC
